platform :ios, '11.0'
use_frameworks!

target 'Progressable_Example' do
  pod 'Progressable', :path => '../'

  target 'Progressable_Tests' do
    inherit! :search_paths
  end
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
